name: CI

on:
  push:

jobs:
  license_check:
    name: License Check
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v4
    - name: Setup pnpm
      uses: pnpm/actions-setup@v2
      with:
        run_install: true
    - name: Check licenses
      run: pnpm script:license-check
